### ISSUE TITLE
Check List

### ISSUE THREAD

**Issue by tJouve** [tJouve/external-dns#3]
- [x] `TestNewPiholeClientV6` fixed
- [x] `TestListRecordsV6` fixed
- [x] `TestCreateRecordV6͘` fixed
- [x] `TestDeleteRecordV6` fixed
- [x] Review
- [ ] Documentation
- [ ] Integration tests
- [ ] Refactoring

**Comment by tJouve** [comment]
@divStar create this issue for discutions.

Think right now we can try to package and run test. I have to check the contribution wiki to find out how to do that.

+ I was thinking it will be better if 
```go
func (p *piholeClientV6) do(req *http.Request) ([]byte, error) 
```

return an ApiErrorResponse instead of a simple err string no ?

**Comment by divStar** [comment]
Having `ApiResponse` (not necessarily just `ApiResponseError`) sounds clean, especially because if external-dns tries to delete something, that isn't there's anyway, this indeed should just be a warning message, not an error.

The `do` method is named a bit poorly. Perhaps something like `queryPihole` or just `query` would be more appropriate? We could take a look at what other providers usually use.

I also can imagine the PiHole provider offering some README.md to explain how it works - I could write it if you're ok with it.

As for building and packaging - perhaps you could use the GitHub Actions workflow built into this project anyway? - just build a custom version and it'll either deploy an artifact to your GitHub packages associated with the Repo or something. But you're right - we need to find out how it's built. I wonder if we could even produce the artifact locally and then stuff it into a cluster for testing (I have a cluster, that I could test it with).
There's also a guy in https://github.com/kubernetes-sigs/external-dns/issues/5113#issuecomment-2687359321, who would also like to test this branch once available.

**Comment by tJouve** [comment]
Found it here => https://github.com/kubernetes-sigs/external-dns/blob/master/docs/contributing/dev-guide.md


```bash 
└─[$] make test                                                                                                         
go test -race -coverprofile=profile.cov ./...
        sigs.k8s.io/external-dns                coverage: 0.0% of statements
ok      sigs.k8s.io/external-dns/controller     2.635s  coverage: 85.8% of statements
ok      sigs.k8s.io/external-dns/endpoint       1.121s  coverage: 63.3% of statements
?       sigs.k8s.io/external-dns/internal/config        [no test files]
ok      sigs.k8s.io/external-dns/internal/gen/docs/flags        1.137s  coverage: 53.8% of statements
ok      sigs.k8s.io/external-dns/internal/testutils     1.021s  coverage: 25.6% of statements
ok      sigs.k8s.io/external-dns/pkg/apis/externaldns   1.100s  coverage: 99.0% of statements
ok      sigs.k8s.io/external-dns/pkg/apis/externaldns/validation        1.052s  coverage: 63.9% of statements
ok      sigs.k8s.io/external-dns/pkg/rfc2317    1.016s  coverage: 87.0% of statements
        sigs.k8s.io/external-dns/pkg/tlsutils           coverage: 0.0% of statements
ok      sigs.k8s.io/external-dns/plan   1.093s  coverage: 97.1% of statements
ok      sigs.k8s.io/external-dns/provider       1.058s  coverage: 85.3% of statements
ok      sigs.k8s.io/external-dns/provider/akamai        1.055s  coverage: 72.2% of statements
ok      sigs.k8s.io/external-dns/provider/alibabacloud  1.060s  coverage: 70.1% of statements
ok      sigs.k8s.io/external-dns/provider/aws   27.661s coverage: 85.4% of statements
ok      sigs.k8s.io/external-dns/provider/awssd 1.050s  coverage: 82.7% of statements
ok      sigs.k8s.io/external-dns/provider/azure 1.088s  coverage: 79.5% of statements
ok      sigs.k8s.io/external-dns/provider/civo  1.132s  coverage: 84.3% of statements
ok      sigs.k8s.io/external-dns/provider/cloudflare    1.083s  coverage: 75.1% of statements
ok      sigs.k8s.io/external-dns/provider/coredns       1.042s  coverage: 53.9% of statements
ok      sigs.k8s.io/external-dns/provider/designate     1.054s  coverage: 75.0% of statements
ok      sigs.k8s.io/external-dns/provider/digitalocean  1.075s  coverage: 81.8% of statements
ok      sigs.k8s.io/external-dns/provider/dnsimple      1.591s  coverage: 81.4% of statements
ok      sigs.k8s.io/external-dns/provider/exoscale      1.034s  coverage: 68.1% of statements
ok      sigs.k8s.io/external-dns/provider/gandi 1.025s  coverage: 83.9% of statements
ok      sigs.k8s.io/external-dns/provider/godaddy       1.072s  coverage: 61.5% of statements
ok      sigs.k8s.io/external-dns/provider/google        1.081s  coverage: 80.6% of statements
ok      sigs.k8s.io/external-dns/provider/ibmcloud      1.087s  coverage: 75.7% of statements
ok      sigs.k8s.io/external-dns/provider/inmemory      1.025s  coverage: 82.6% of statements
ok      sigs.k8s.io/external-dns/provider/linode        1.037s  coverage: 84.7% of statements
ok      sigs.k8s.io/external-dns/provider/ns1   1.030s  coverage: 81.6% of statements
ok      sigs.k8s.io/external-dns/provider/oci   1.042s  coverage: 75.9% of statements
ok      sigs.k8s.io/external-dns/provider/ovh   5.816s  coverage: 95.5% of statements
ok      sigs.k8s.io/external-dns/provider/pdns  1.064s  coverage: 64.5% of statements
ok      sigs.k8s.io/external-dns/provider/pihole        1.082s  coverage: 74.1% of statements
ok      sigs.k8s.io/external-dns/provider/plural        1.034s  coverage: 31.5% of statements
ok      sigs.k8s.io/external-dns/provider/rfc2136       1.102s  coverage: 56.5% of statements
ok      sigs.k8s.io/external-dns/provider/scaleway      1.050s  coverage: 69.6% of statements
ok      sigs.k8s.io/external-dns/provider/tencentcloud  1.021s  coverage: 84.3% of statements
        sigs.k8s.io/external-dns/provider/tencentcloud/cloudapi         coverage: 0.0% of statements
ok      sigs.k8s.io/external-dns/provider/transip       1.052s  coverage: 40.7% of statements
ok      sigs.k8s.io/external-dns/provider/ultradns      1.041s  coverage: 81.9% of statements
ok      sigs.k8s.io/external-dns/provider/webhook       1.052s  coverage: 65.9% of statements
ok      sigs.k8s.io/external-dns/provider/webhook/api   1.035s  coverage: 89.7% of statements
ok      sigs.k8s.io/external-dns/registry       1.233s  coverage: 89.8% of statements
ok      sigs.k8s.io/external-dns/source 9.146s  coverage: 76.0% of statements
```

**Comment by tJouve** [comment]
make generate-flags-documentation

The Flag APIVersion is not declared in the documentation 

=> https://github.com/tJouve/external-dns/pull/4

**Comment by tJouve** [comment]
I have create a image based on https://github.com/tJouve/external-dns/pull/4

tjouve/external-dns:6a4d8474

I change my values file by adding : 

```yaml
    image:
      repository: tjouve/external-dns
      tag: 6a4d8474
```

And
```yaml
    env:
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        value: "6"
```

**Comment by divStar** [comment]
@tJouve from the logs I cannot see if you have checked whether CNAME or A/AAAA records are added / removed automatically using `external-dns` when adding / removing e.g. Deployment (or Service, StatefulSet or similar eligible) resources? I guess I'll give it a try tomorrow, too.

**Comment by tJouve** [comment]
My test file : 

```yaml
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ext-test-a-internal
  labels:
    external-dns.smokingcat.net/visibility: private
spec:
  endpoints:
  - dnsName: testA.smokingcat.net
    recordType: A
    targets:
    - 192.168.0.1
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ext-test-cname-internal
  labels:
    external-dns.smokingcat.net/visibility: private
spec:
  endpoints:
  - dnsName: testCNAME.smokingcat.net
    recordType: CNAME
    recordTTL: 180
    targets:
    - testA.smokingcat.net
```
```bash
└─[$] k apply -f test.yaml
dnsendpoint.externaldns.k8s.io "ext-test-a-internal" created
dnsendpoint.externaldns.k8s.io "ext-test-cname-internal" created
```
![Image](https://github.com/user-attachments/assets/169bf8c3-ed3b-4ebd-838c-ce55438d8338)

```bash
└─[$] dig testA.smokingcat.net                                                                                                                                

; <<>> DiG 9.20.4-4-Debian <<>> testA.smokingcat.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17801
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;testA.smokingcat.net.          IN      A

;; ANSWER SECTION:
testA.smokingcat.net.   0       IN      A       192.168.0.1

;; Query time: 7 msec
;; SERVER: 192.168.0.1#53(192.168.0.1) (UDP)
;; WHEN: Sun Mar 02 23:15:29 CET 2025
;; MSG SIZE  rcvd: 65

└─[$] dig testCNAME.smokingcat.net                                                                                                                           

; <<>> DiG 9.20.4-4-Debian <<>> testCNAME.smokingcat.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54923
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;testCNAME.smokingcat.net.      IN      A

;; ANSWER SECTION:
testCNAME.smokingcat.net. 180   IN      CNAME   testa.smokingcat.net.
testa.smokingcat.net.   0       IN      A       192.168.0.1

;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1) (UDP)
;; WHEN: Sun Mar 02 23:15:35 CET 2025
;; MSG SIZE  rcvd: 89
```

![Image](https://github.com/user-attachments/assets/d9f46347-1811-4944-963c-4f56225c9f1a)

```bash
└─[$] k delete -f test.yaml
dnsendpoint.externaldns.k8s.io "ext-test-a-internal" deleted
dnsendpoint.externaldns.k8s.io "ext-test-cname-internal" deleted
```

![Image](https://github.com/user-attachments/assets/0dc9ccc4-af4c-4a5e-9ee6-b0f8cb53aa4f)

**Comment by divStar** [comment]
This looks awesome! As mentioned before, I'll definitely try this out tomorrow. I have to install a new instance of PiHole (v6) on my new server, because I've had issues with my old server.

**Comment by tJouve** [comment]
Yes now TTL is working for CNAME :-D

Now Edge case scenarios :-D

**Comment by heschlie** [comment]
Hey @tJouve thanks for the work on this! Would I be able to con you into pushing an ARM image to test?

**Comment by divStar** [comment]
I've finally managed to take some time to test this. I use `Cilium` and now `external-dns` (and a couple others).

h3. **Case 1:** creating Ingress resource without any annotations
When creating **Ingress resources**, their host entries are **not** added - even with `policy: sync` they do **not** get added. Also nothing happens when deleting the Ingress resources.

h3. **Case 2:** creating Ingress resource *with* annotations
Creating an Ingress resource with the following:
```yaml
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.178.223
```
works! It creates and deletes the Ingress resource as expected.

h3. **Case 3:** creating multiple Ingress resources *with* annotations (same host, different `target`, both within 1 interval)
This works, too. However: I am not sure which one is picked up.

I had defined two resources:

<details>
<summary>Ingress resource 1</summary>

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-ingress-1
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.178.222  # Use your node IP
spec:
  ingressClassName: nginx  # Use your ingress controller class name
  rules:
  - host: test-ingress.my.world
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes
            port:
              number: 443
```
</details>
and
<details>
<summary>Ingress resource 2</summary>

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy-ingress-2
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.178.223  # Use your node IP
spec:
  ingressClassName: nginx  # Use your ingress controller class name
  rules:
  - host: test-ingress.my.world
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubernetes
            port:
              number: 443
```
*Note:* only `metadata.name` and `metadata.annotations.external-dns.alpha.kubernetes.io/target` differ.
</details>

When I add both during one interval (e.g. within 60 seconds), the **first Ingress resource** is picked up, but I don't know if that's always the case.

h3. **Case 4:** creating multiple Ingress resources *with* annotations (same host, different `target`, 2 intervals)
Case 4 leans on case 3, but the resources are not applied within one interval, but within 2.
The host / target of the second resource does **not** seem to be processed at all.

*However:* when I deleted the first resource (that supposedly was used to create the A record in PiHole), at the next interval that A record was deleted. Right after that the A record for the remaining resource (the second one) was re-applied automatically - which is great, because this way the Ingress resource now still has access and the host / target combination is used, that the 2nd Ingress resource actually contains.

Deleting the 2nd Ingress resource also removes the A record as expected.

h3. Service resources
`Service` resources seem to behave the same as `Ingress` resources. I have not tested CNAME records though and I have **not** created any `DNSEndpoint` resources (I didn't even know one could do that).

h3. **TL;DR**
Ingress and Service resources **with annotations** are processed correctly from what I can tell. However: I *only* tried `A` records, not `AAAA` records or `CNAME` entries. Even if using the same host with multiple `target` annotations, it seems, that the first one is used and the others are ignored *until* the first one does not exist anymore. Once the first resource does not exist anymore, the second one (if still available) kicks in and the `A` record is removed (because the first resource is removed) and then re-added (from the second resource).
